language: node_js
node_js:
  - '12'

cache:
  yarn: true
  directories:
    - 'node_modules'

branches:
  only:
    - master

install:
  - yarn install
  - yarn run build

script:
  - echo "No tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master
